[project]
name = "ezhpcy"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    # Pydantic
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.14.2",
    "pydantic>=2.13.4",

    # Build system
    "hatchling>=1.31.0",
    "jinja2>=3.1.6",

    # Networking
    "paramiko>=4.0.0",
    "requests>=2.34.2",

    # CLI
    "rich>=15.0.0",
    "typer>=0.26.8",

    # Keyring, secretstorage is for keyring on Linux
    "keyring>=25.7.0",
    "secretstorage>=3.5.0 ; sys_platform == 'linux'",
]

[project.scripts]
ezhpcy = "ezhpcy.cli.entry:main"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pytest>=9.1.1",
    "ruff>=0.15.21",
]

[tool.ruff.lint]
extend-select = ["I"]
isort.combine-as-imports = true

[build-system]
requires = ["hatchling>=1.31,<2"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ezhpcy"]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "/PKG-INFO",
    "/dist",
]
