[project]
name = "ezhpcy"
version = "0.1.0"
requires-python = ">=3.15"
dependencies = [
    # Pydantic
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.14.2",
    "pydantic>=2.13.5",
    # Templates
    "jinja2>=3.1.6",
    # SSH
    "paramiko>=4.0.0",
    "cryptography>=46.0.5",
    # CLI
    "rich>=15.0.0",
    "typer>=0.27.2",
    "cyclopts>=5.1.1",
    # Keyring, secretstorage is for keyring on Linux
    "keyring>=25.7.0",
    "secretstorage>=3.5.0 ; sys_platform == 'linux'",
    # Utils
    "py-machineid>=1.0.0",
    "platformdirs>=4.9.4",
]

[project.scripts]
ezhpcy = "ezhpcy.cli:main"

[dependency-groups]
dev = [
    "prek>=0.4.9",
    "pytest>=9.1.1",
    "ruff>=0.16.10", # keep in sync with .pre-commit-config.yaml
]

[tool.ruff.lint]
preview = true
extend-select = [
    "I",   # isort
    "UP",  # pyupgrade
    "TID", # flake8-tidy-imports
    "YTT", # flake8-2020
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "DTZ",  # flake8-datetimetz
    "T10", #flake8-debugger
    "EXE", #flake8-executable
    "LOG", #flake8-logging
    "INP", #flake8-no-pep420
]
ignore = [
    "RUF106",  # rule-codecs-in-suppression-comments
]
isort.combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
# Tests
"tests/**" = [
    "RUF069",  # float-equality-comparison, in tests we sometimes want eq. check
]

# Standalone scripts
"scripts/**" = [
    "INP",  # no-pep420, scripts are standalone and not part of a package
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12"]
build-backend = "uv_build"
